version: '3'
services:
  app:
    build: .
    container_name: bakalarka-app
    ports:
      - "5000:5000"
    environment:
      # Tu môžeme definovať premenné, ktoré inak máš v .env
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/bakalarka
      - AI_API=ef2dc5a0acmsh73c25639b80ca35p1547d0jsn77ba64612543
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=bakalarka
